{
  try {
    resetInternal();
  }
 catch (  SAXNotRecognizedException e) {
    throw new AssertionError();
  }
catch (  SAXNotSupportedException e) {
    throw new AssertionError();
  }
}
