{
  try {
    super.finalize();
  }
 catch (  Throwable t) {
    throw new AssertionError(t);
  }
}
