{
  try {
    printStackTrace(err,"",null);
  }
 catch (  IOException e) {
    throw new AssertionError();
  }
}
