{
  try {
    ctx.terminate();
    Thread.currentThread().interrupt();
  }
 catch (  ObjectInUseException e) {
    sipStack.getStackLogger().logError("unexpected error",e);
  }
}
